apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-app
spec:
  replicas: 2 # Number of replicas
  selector:
    matchLabels:
      app: bun
  template:
    metadata:
      labels:
        app: bun
    spec:
    containers:
    - name: bun-container
      image: bnkregistry.azurecr.io/bnk-payments-stack:latest
      ports:
      - containerPort: 80
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "200m"
          memory: "256Mi"

