# fly.toml app configuration file generated for htmlody-template on 2023-10-24T12:48:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "htmlody-template"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
