name: Azure Deploy AppContainer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_REGISTRY_NAME: ${{ secrets.AZURE_REGISTRY_NAME }}
      AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      AZURE_CONTAINER_ENVIRONMENT: ${{ secrets.AZURE_CONTAINER_ENV }}

    steps:
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Run Azure Deploy
        run: bun azure-dpeloy.ts